version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: djangodb
      MYSQL_USER: test-user
      MYSQL_PASSWORD: this.is.just.the.testing.password
      MYSQL_ROOT_PASSWORD: this.is.just.the.root.password
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-sample-app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: